/* Generated by Yosys 0.66+154 (git sha1 23aadd92a, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* dynports =  1  *)
(* hdlname = "fifo_memory" *)
(* src = "rtl/fifo_memory.v:1.1-32.10" *)
module \$paramod$6a1231bad6349c99ef10c6a6a58dbbf16b7d2bdb\fifo_memory (clk, wr_en, rd_en, wr_data, wr_ptr, rd_ptr, rd_data);
  (* src = "rtl/fifo_memory.v:6.37-6.40" *)
  input clk;
  wire clk;
  (* src = "rtl/fifo_memory.v:7.37-7.42" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/fifo_memory.v:8.37-8.42" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/fifo_memory.v:10.37-10.44" *)
  input [7:0] wr_data;
  wire [7:0] wr_data;
  (* src = "rtl/fifo_memory.v:12.37-12.43" *)
  input [3:0] wr_ptr;
  wire [3:0] wr_ptr;
  (* src = "rtl/fifo_memory.v:13.37-13.43" *)
  input [3:0] rd_ptr;
  wire [3:0] rd_ptr;
  (* src = "rtl/fifo_memory.v:15.37-15.44" *)
  output [7:0] rd_data;
  reg [7:0] rd_data;
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  assign _017_ = ~(rd_ptr[2] & \mem[14] [6]);
  assign _018_ = \mem[10] [6] & ~(rd_ptr[2]);
  assign _019_ = ~(rd_ptr[0] | _018_);
  assign _020_ = ~(_017_ & _019_);
  assign _021_ = ~(rd_ptr[2] & \mem[15] [6]);
  assign _022_ = rd_ptr[2] | ~(\mem[11] [6]);
  assign _023_ = rd_ptr[0] & _022_;
  assign _024_ = ~(_021_ & _023_);
  assign _025_ = _020_ & _024_;
  assign _026_ = rd_ptr[2] ? \mem[7] [6] : \mem[3] [6];
  assign _027_ = rd_ptr[2] ? \mem[6] [6] : \mem[2] [6];
  assign _028_ = rd_ptr[0] ? _026_ : _027_;
  assign _029_ = rd_ptr[3] ? _025_ : _028_;
  assign _030_ = rd_ptr[2] ? \mem[12] [6] : \mem[8] [6];
  assign _031_ = rd_ptr[2] ? \mem[13] [6] : \mem[9] [6];
  assign _032_ = rd_ptr[0] ? _031_ : _030_;
  assign _033_ = rd_ptr[2] ? \mem[5] [6] : \mem[1] [6];
  assign _034_ = rd_ptr[2] ? \mem[4] [6] : \mem[0] [6];
  assign _035_ = rd_ptr[0] ? _033_ : _034_;
  assign _036_ = rd_ptr[3] ? _032_ : _035_;
  assign _000_[6] = rd_ptr[1] ? _029_ : _036_;
  assign _037_ = rd_ptr[2] ? \mem[7] [5] : \mem[3] [5];
  assign _038_ = rd_ptr[2] ? \mem[6] [5] : \mem[2] [5];
  assign _039_ = rd_ptr[0] ? _037_ : _038_;
  assign _040_ = rd_ptr[2] ? \mem[5] [5] : \mem[1] [5];
  assign _041_ = rd_ptr[2] ? \mem[4] [5] : \mem[0] [5];
  assign _042_ = rd_ptr[0] ? _040_ : _041_;
  assign _043_ = rd_ptr[1] ? _039_ : _042_;
  assign _044_ = rd_ptr[2] ? \mem[12] [5] : \mem[8] [5];
  assign _045_ = rd_ptr[2] ? \mem[13] [5] : \mem[9] [5];
  assign _046_ = rd_ptr[0] ? _045_ : _044_;
  assign _047_ = rd_ptr[1] | _046_;
  assign _048_ = rd_ptr[2] ? \mem[15] [5] : \mem[11] [5];
  assign _049_ = ~(rd_ptr[0] & _048_);
  assign _050_ = rd_ptr[2] ? \mem[14] [5] : \mem[10] [5];
  assign _051_ = rd_ptr[0] | ~(_050_);
  assign _052_ = rd_ptr[1] & _051_;
  assign _053_ = ~(_049_ & _052_);
  assign _054_ = _047_ & _053_;
  assign _000_[5] = rd_ptr[3] ? _054_ : _043_;
  assign _055_ = ~(rd_ptr[2] & \mem[14] [4]);
  assign _056_ = \mem[10] [4] & ~(rd_ptr[2]);
  assign _057_ = ~(rd_ptr[0] | _056_);
  assign _058_ = ~(_055_ & _057_);
  assign _059_ = ~(rd_ptr[2] & \mem[15] [4]);
  assign _060_ = rd_ptr[2] | ~(\mem[11] [4]);
  assign _061_ = rd_ptr[0] & _060_;
  assign _062_ = ~(_059_ & _061_);
  assign _063_ = _058_ & _062_;
  assign _064_ = rd_ptr[2] ? \mem[7] [4] : \mem[3] [4];
  assign _065_ = rd_ptr[2] ? \mem[6] [4] : \mem[2] [4];
  assign _066_ = rd_ptr[0] ? _064_ : _065_;
  assign _067_ = rd_ptr[3] ? _063_ : _066_;
  assign _068_ = rd_ptr[2] ? \mem[12] [4] : \mem[8] [4];
  assign _069_ = rd_ptr[2] ? \mem[13] [4] : \mem[9] [4];
  assign _070_ = rd_ptr[0] ? _069_ : _068_;
  assign _071_ = rd_ptr[2] ? \mem[5] [4] : \mem[1] [4];
  assign _072_ = rd_ptr[2] ? \mem[4] [4] : \mem[0] [4];
  assign _073_ = rd_ptr[0] ? _071_ : _072_;
  assign _074_ = rd_ptr[3] ? _070_ : _073_;
  assign _000_[4] = rd_ptr[1] ? _067_ : _074_;
  assign _075_ = rd_ptr[2] ? \mem[7] [3] : \mem[3] [3];
  assign _076_ = rd_ptr[2] ? \mem[6] [3] : \mem[2] [3];
  assign _077_ = rd_ptr[0] ? _075_ : _076_;
  assign _078_ = rd_ptr[2] ? \mem[5] [3] : \mem[1] [3];
  assign _079_ = rd_ptr[2] ? \mem[4] [3] : \mem[0] [3];
  assign _080_ = rd_ptr[0] ? _078_ : _079_;
  assign _081_ = rd_ptr[1] ? _077_ : _080_;
  assign _082_ = rd_ptr[2] ? \mem[12] [3] : \mem[8] [3];
  assign _083_ = rd_ptr[2] ? \mem[13] [3] : \mem[9] [3];
  assign _084_ = rd_ptr[0] ? _083_ : _082_;
  assign _085_ = rd_ptr[1] | _084_;
  assign _086_ = rd_ptr[2] ? \mem[15] [3] : \mem[11] [3];
  assign _087_ = ~(rd_ptr[0] & _086_);
  assign _088_ = rd_ptr[2] ? \mem[14] [3] : \mem[10] [3];
  assign _089_ = rd_ptr[0] | ~(_088_);
  assign _090_ = rd_ptr[1] & _089_;
  assign _091_ = ~(_087_ & _090_);
  assign _092_ = _085_ & _091_;
  assign _000_[3] = rd_ptr[3] ? _092_ : _081_;
  assign _093_ = rd_ptr[2] | ~(\mem[10] [2]);
  assign _094_ = rd_ptr[2] & \mem[14] [2];
  assign _095_ = ~(rd_ptr[0] | _094_);
  assign _096_ = ~(_093_ & _095_);
  assign _097_ = rd_ptr[2] | ~(\mem[11] [2]);
  assign _098_ = ~(rd_ptr[2] & \mem[15] [2]);
  assign _099_ = rd_ptr[0] & _098_;
  assign _100_ = ~(_097_ & _099_);
  assign _101_ = _096_ & _100_;
  assign _102_ = rd_ptr[2] ? \mem[13] [2] : \mem[9] [2];
  assign _103_ = rd_ptr[2] ? \mem[12] [2] : \mem[8] [2];
  assign _104_ = rd_ptr[0] ? _102_ : _103_;
  assign _105_ = rd_ptr[1] ? _101_ : _104_;
  assign _106_ = rd_ptr[2] ? \mem[6] [2] : \mem[2] [2];
  assign _107_ = rd_ptr[0] | _106_;
  assign _108_ = rd_ptr[2] | ~(\mem[3] [2]);
  assign _109_ = ~(rd_ptr[2] & \mem[7] [2]);
  assign _110_ = rd_ptr[0] & _109_;
  assign _111_ = ~(_108_ & _110_);
  assign _112_ = _107_ & _111_;
  assign _113_ = rd_ptr[2] ? \mem[5] [2] : \mem[1] [2];
  assign _114_ = rd_ptr[2] ? \mem[4] [2] : \mem[0] [2];
  assign _115_ = rd_ptr[0] ? _113_ : _114_;
  assign _116_ = rd_ptr[1] ? _112_ : _115_;
  assign _000_[2] = rd_ptr[3] ? _105_ : _116_;
  assign _117_ = rd_ptr[2] ? \mem[7] [1] : \mem[3] [1];
  assign _118_ = rd_ptr[2] ? \mem[6] [1] : \mem[2] [1];
  assign _119_ = rd_ptr[2] ? \mem[5] [1] : \mem[1] [1];
  assign _120_ = rd_ptr[2] ? \mem[4] [1] : \mem[0] [1];
  assign _121_ = rd_ptr[0] ? _119_ : _120_;
  assign _122_ = rd_ptr[2] ? \mem[15] [1] : \mem[11] [1];
  assign _123_ = ~(rd_ptr[0] & _122_);
  assign _124_ = rd_ptr[2] ? \mem[14] [1] : \mem[10] [1];
  assign _125_ = rd_ptr[0] | ~(_124_);
  assign _126_ = rd_ptr[1] & _125_;
  assign _127_ = ~(_123_ & _126_);
  assign _128_ = rd_ptr[2] ? \mem[12] [1] : \mem[8] [1];
  assign _129_ = rd_ptr[0] | ~(_128_);
  assign _130_ = rd_ptr[2] ? \mem[13] [1] : \mem[9] [1];
  assign _131_ = rd_ptr[0] & _130_;
  assign _132_ = ~(rd_ptr[1] | _131_);
  assign _133_ = ~(_129_ & _132_);
  assign _134_ = _127_ & _133_;
  assign _135_ = rd_ptr[1] | _121_;
  assign _136_ = rd_ptr[0] | ~(_118_);
  assign _137_ = ~(rd_ptr[0] & _117_);
  assign _138_ = rd_ptr[1] & _137_;
  assign _139_ = ~(_136_ & _138_);
  assign _140_ = _135_ & _139_;
  assign _000_[1] = rd_ptr[3] ? _134_ : _140_;
  assign _141_ = ~(rd_ptr[2] & \mem[14] [0]);
  assign _142_ = \mem[10] [0] & ~(rd_ptr[2]);
  assign _143_ = ~(rd_ptr[0] | _142_);
  assign _144_ = ~(_141_ & _143_);
  assign _145_ = ~(rd_ptr[2] & \mem[15] [0]);
  assign _146_ = rd_ptr[2] | ~(\mem[11] [0]);
  assign _147_ = rd_ptr[0] & _146_;
  assign _148_ = ~(_145_ & _147_);
  assign _149_ = _144_ & _148_;
  assign _150_ = rd_ptr[2] ? \mem[7] [0] : \mem[3] [0];
  assign _151_ = rd_ptr[2] ? \mem[6] [0] : \mem[2] [0];
  assign _152_ = rd_ptr[0] ? _150_ : _151_;
  assign _153_ = rd_ptr[3] ? _149_ : _152_;
  assign _154_ = rd_ptr[2] ? \mem[12] [0] : \mem[8] [0];
  assign _155_ = rd_ptr[2] ? \mem[13] [0] : \mem[9] [0];
  assign _156_ = rd_ptr[0] ? _155_ : _154_;
  assign _157_ = rd_ptr[2] ? \mem[5] [0] : \mem[1] [0];
  assign _158_ = rd_ptr[2] ? \mem[4] [0] : \mem[0] [0];
  assign _159_ = rd_ptr[0] ? _157_ : _158_;
  assign _160_ = rd_ptr[3] ? _156_ : _159_;
  assign _000_[0] = rd_ptr[1] ? _153_ : _160_;
  assign _161_ = wr_ptr[3] & ~(wr_ptr[2]);
  assign _162_ = wr_en & ~(wr_ptr[1]);
  assign _163_ = _162_ & ~(wr_ptr[0]);
  assign _015_ = _161_ & _163_;
  assign _164_ = wr_ptr[3] & wr_ptr[2];
  assign _165_ = wr_en & wr_ptr[1];
  assign _166_ = wr_ptr[0] & _165_;
  assign _007_ = _164_ & _166_;
  assign _167_ = wr_ptr[2] & ~(wr_ptr[3]);
  assign _014_ = _166_ & _167_;
  assign _168_ = _165_ & ~(wr_ptr[0]);
  assign _013_ = _167_ & _168_;
  assign _004_ = _163_ & _164_;
  assign _169_ = wr_ptr[0] & _162_;
  assign _012_ = _167_ & _169_;
  assign _011_ = _163_ & _167_;
  assign _170_ = ~(wr_ptr[3] | wr_ptr[2]);
  assign _010_ = _166_ & _170_;
  assign _005_ = _164_ & _169_;
  assign _009_ = _168_ & _170_;
  assign _003_ = _161_ & _166_;
  assign _008_ = _169_ & _170_;
  assign _006_ = _164_ & _168_;
  assign _002_ = _161_ & _168_;
  assign _001_ = _163_ & _170_;
  assign _171_ = ~(rd_ptr[2] & \mem[14] [7]);
  assign _172_ = \mem[10] [7] & ~(rd_ptr[2]);
  assign _173_ = ~(rd_ptr[0] | _172_);
  assign _174_ = ~(_171_ & _173_);
  assign _175_ = ~(rd_ptr[2] & \mem[15] [7]);
  assign _176_ = rd_ptr[2] | ~(\mem[11] [7]);
  assign _177_ = rd_ptr[0] & _176_;
  assign _178_ = ~(_175_ & _177_);
  assign _179_ = _174_ & _178_;
  assign _180_ = rd_ptr[2] ? \mem[7] [7] : \mem[3] [7];
  assign _181_ = rd_ptr[2] ? \mem[6] [7] : \mem[2] [7];
  assign _182_ = rd_ptr[0] ? _180_ : _181_;
  assign _183_ = rd_ptr[3] ? _179_ : _182_;
  assign _184_ = rd_ptr[2] ? \mem[12] [7] : \mem[8] [7];
  assign _185_ = rd_ptr[2] ? \mem[13] [7] : \mem[9] [7];
  assign _186_ = rd_ptr[0] ? _185_ : _184_;
  assign _187_ = rd_ptr[2] ? \mem[5] [7] : \mem[1] [7];
  assign _188_ = rd_ptr[2] ? \mem[4] [7] : \mem[0] [7];
  assign _189_ = rd_ptr[0] ? _187_ : _188_;
  assign _190_ = rd_ptr[3] ? _186_ : _189_;
  assign _000_[7] = rd_ptr[1] ? _183_ : _190_;
  assign _016_ = _161_ & _169_;
  always @(posedge clk)
    if (rd_en) rd_data[0] <= _000_[0];
  always @(posedge clk)
    if (rd_en) rd_data[1] <= _000_[1];
  always @(posedge clk)
    if (rd_en) rd_data[2] <= _000_[2];
  always @(posedge clk)
    if (rd_en) rd_data[3] <= _000_[3];
  always @(posedge clk)
    if (rd_en) rd_data[4] <= _000_[4];
  always @(posedge clk)
    if (rd_en) rd_data[5] <= _000_[5];
  always @(posedge clk)
    if (rd_en) rd_data[6] <= _000_[6];
  always @(posedge clk)
    if (rd_en) rd_data[7] <= _000_[7];
  always @(posedge clk)
    if (_007_) \mem[15] [0] <= wr_data[0];
  always @(posedge clk)
    if (_007_) \mem[15] [1] <= wr_data[1];
  always @(posedge clk)
    if (_007_) \mem[15] [2] <= wr_data[2];
  always @(posedge clk)
    if (_007_) \mem[15] [3] <= wr_data[3];
  always @(posedge clk)
    if (_007_) \mem[15] [4] <= wr_data[4];
  always @(posedge clk)
    if (_007_) \mem[15] [5] <= wr_data[5];
  always @(posedge clk)
    if (_007_) \mem[15] [6] <= wr_data[6];
  always @(posedge clk)
    if (_007_) \mem[15] [7] <= wr_data[7];
  always @(posedge clk)
    if (_006_) \mem[14] [0] <= wr_data[0];
  always @(posedge clk)
    if (_006_) \mem[14] [1] <= wr_data[1];
  always @(posedge clk)
    if (_006_) \mem[14] [2] <= wr_data[2];
  always @(posedge clk)
    if (_006_) \mem[14] [3] <= wr_data[3];
  always @(posedge clk)
    if (_006_) \mem[14] [4] <= wr_data[4];
  always @(posedge clk)
    if (_006_) \mem[14] [5] <= wr_data[5];
  always @(posedge clk)
    if (_006_) \mem[14] [6] <= wr_data[6];
  always @(posedge clk)
    if (_006_) \mem[14] [7] <= wr_data[7];
  always @(posedge clk)
    if (_005_) \mem[13] [0] <= wr_data[0];
  always @(posedge clk)
    if (_005_) \mem[13] [1] <= wr_data[1];
  always @(posedge clk)
    if (_005_) \mem[13] [2] <= wr_data[2];
  always @(posedge clk)
    if (_005_) \mem[13] [3] <= wr_data[3];
  always @(posedge clk)
    if (_005_) \mem[13] [4] <= wr_data[4];
  always @(posedge clk)
    if (_005_) \mem[13] [5] <= wr_data[5];
  always @(posedge clk)
    if (_005_) \mem[13] [6] <= wr_data[6];
  always @(posedge clk)
    if (_005_) \mem[13] [7] <= wr_data[7];
  always @(posedge clk)
    if (_004_) \mem[12] [0] <= wr_data[0];
  always @(posedge clk)
    if (_004_) \mem[12] [1] <= wr_data[1];
  always @(posedge clk)
    if (_004_) \mem[12] [2] <= wr_data[2];
  always @(posedge clk)
    if (_004_) \mem[12] [3] <= wr_data[3];
  always @(posedge clk)
    if (_004_) \mem[12] [4] <= wr_data[4];
  always @(posedge clk)
    if (_004_) \mem[12] [5] <= wr_data[5];
  always @(posedge clk)
    if (_004_) \mem[12] [6] <= wr_data[6];
  always @(posedge clk)
    if (_004_) \mem[12] [7] <= wr_data[7];
  always @(posedge clk)
    if (_003_) \mem[11] [0] <= wr_data[0];
  always @(posedge clk)
    if (_003_) \mem[11] [1] <= wr_data[1];
  always @(posedge clk)
    if (_003_) \mem[11] [2] <= wr_data[2];
  always @(posedge clk)
    if (_003_) \mem[11] [3] <= wr_data[3];
  always @(posedge clk)
    if (_003_) \mem[11] [4] <= wr_data[4];
  always @(posedge clk)
    if (_003_) \mem[11] [5] <= wr_data[5];
  always @(posedge clk)
    if (_003_) \mem[11] [6] <= wr_data[6];
  always @(posedge clk)
    if (_003_) \mem[11] [7] <= wr_data[7];
  always @(posedge clk)
    if (_002_) \mem[10] [0] <= wr_data[0];
  always @(posedge clk)
    if (_002_) \mem[10] [1] <= wr_data[1];
  always @(posedge clk)
    if (_002_) \mem[10] [2] <= wr_data[2];
  always @(posedge clk)
    if (_002_) \mem[10] [3] <= wr_data[3];
  always @(posedge clk)
    if (_002_) \mem[10] [4] <= wr_data[4];
  always @(posedge clk)
    if (_002_) \mem[10] [5] <= wr_data[5];
  always @(posedge clk)
    if (_002_) \mem[10] [6] <= wr_data[6];
  always @(posedge clk)
    if (_002_) \mem[10] [7] <= wr_data[7];
  always @(posedge clk)
    if (_016_) \mem[9] [0] <= wr_data[0];
  always @(posedge clk)
    if (_016_) \mem[9] [1] <= wr_data[1];
  always @(posedge clk)
    if (_016_) \mem[9] [2] <= wr_data[2];
  always @(posedge clk)
    if (_016_) \mem[9] [3] <= wr_data[3];
  always @(posedge clk)
    if (_016_) \mem[9] [4] <= wr_data[4];
  always @(posedge clk)
    if (_016_) \mem[9] [5] <= wr_data[5];
  always @(posedge clk)
    if (_016_) \mem[9] [6] <= wr_data[6];
  always @(posedge clk)
    if (_016_) \mem[9] [7] <= wr_data[7];
  always @(posedge clk)
    if (_015_) \mem[8] [0] <= wr_data[0];
  always @(posedge clk)
    if (_015_) \mem[8] [1] <= wr_data[1];
  always @(posedge clk)
    if (_015_) \mem[8] [2] <= wr_data[2];
  always @(posedge clk)
    if (_015_) \mem[8] [3] <= wr_data[3];
  always @(posedge clk)
    if (_015_) \mem[8] [4] <= wr_data[4];
  always @(posedge clk)
    if (_015_) \mem[8] [5] <= wr_data[5];
  always @(posedge clk)
    if (_015_) \mem[8] [6] <= wr_data[6];
  always @(posedge clk)
    if (_015_) \mem[8] [7] <= wr_data[7];
  always @(posedge clk)
    if (_014_) \mem[7] [0] <= wr_data[0];
  always @(posedge clk)
    if (_014_) \mem[7] [1] <= wr_data[1];
  always @(posedge clk)
    if (_014_) \mem[7] [2] <= wr_data[2];
  always @(posedge clk)
    if (_014_) \mem[7] [3] <= wr_data[3];
  always @(posedge clk)
    if (_014_) \mem[7] [4] <= wr_data[4];
  always @(posedge clk)
    if (_014_) \mem[7] [5] <= wr_data[5];
  always @(posedge clk)
    if (_014_) \mem[7] [6] <= wr_data[6];
  always @(posedge clk)
    if (_014_) \mem[7] [7] <= wr_data[7];
  always @(posedge clk)
    if (_013_) \mem[6] [0] <= wr_data[0];
  always @(posedge clk)
    if (_013_) \mem[6] [1] <= wr_data[1];
  always @(posedge clk)
    if (_013_) \mem[6] [2] <= wr_data[2];
  always @(posedge clk)
    if (_013_) \mem[6] [3] <= wr_data[3];
  always @(posedge clk)
    if (_013_) \mem[6] [4] <= wr_data[4];
  always @(posedge clk)
    if (_013_) \mem[6] [5] <= wr_data[5];
  always @(posedge clk)
    if (_013_) \mem[6] [6] <= wr_data[6];
  always @(posedge clk)
    if (_013_) \mem[6] [7] <= wr_data[7];
  always @(posedge clk)
    if (_012_) \mem[5] [0] <= wr_data[0];
  always @(posedge clk)
    if (_012_) \mem[5] [1] <= wr_data[1];
  always @(posedge clk)
    if (_012_) \mem[5] [2] <= wr_data[2];
  always @(posedge clk)
    if (_012_) \mem[5] [3] <= wr_data[3];
  always @(posedge clk)
    if (_012_) \mem[5] [4] <= wr_data[4];
  always @(posedge clk)
    if (_012_) \mem[5] [5] <= wr_data[5];
  always @(posedge clk)
    if (_012_) \mem[5] [6] <= wr_data[6];
  always @(posedge clk)
    if (_012_) \mem[5] [7] <= wr_data[7];
  always @(posedge clk)
    if (_011_) \mem[4] [0] <= wr_data[0];
  always @(posedge clk)
    if (_011_) \mem[4] [1] <= wr_data[1];
  always @(posedge clk)
    if (_011_) \mem[4] [2] <= wr_data[2];
  always @(posedge clk)
    if (_011_) \mem[4] [3] <= wr_data[3];
  always @(posedge clk)
    if (_011_) \mem[4] [4] <= wr_data[4];
  always @(posedge clk)
    if (_011_) \mem[4] [5] <= wr_data[5];
  always @(posedge clk)
    if (_011_) \mem[4] [6] <= wr_data[6];
  always @(posedge clk)
    if (_011_) \mem[4] [7] <= wr_data[7];
  always @(posedge clk)
    if (_010_) \mem[3] [0] <= wr_data[0];
  always @(posedge clk)
    if (_010_) \mem[3] [1] <= wr_data[1];
  always @(posedge clk)
    if (_010_) \mem[3] [2] <= wr_data[2];
  always @(posedge clk)
    if (_010_) \mem[3] [3] <= wr_data[3];
  always @(posedge clk)
    if (_010_) \mem[3] [4] <= wr_data[4];
  always @(posedge clk)
    if (_010_) \mem[3] [5] <= wr_data[5];
  always @(posedge clk)
    if (_010_) \mem[3] [6] <= wr_data[6];
  always @(posedge clk)
    if (_010_) \mem[3] [7] <= wr_data[7];
  always @(posedge clk)
    if (_009_) \mem[2] [0] <= wr_data[0];
  always @(posedge clk)
    if (_009_) \mem[2] [1] <= wr_data[1];
  always @(posedge clk)
    if (_009_) \mem[2] [2] <= wr_data[2];
  always @(posedge clk)
    if (_009_) \mem[2] [3] <= wr_data[3];
  always @(posedge clk)
    if (_009_) \mem[2] [4] <= wr_data[4];
  always @(posedge clk)
    if (_009_) \mem[2] [5] <= wr_data[5];
  always @(posedge clk)
    if (_009_) \mem[2] [6] <= wr_data[6];
  always @(posedge clk)
    if (_009_) \mem[2] [7] <= wr_data[7];
  always @(posedge clk)
    if (_008_) \mem[1] [0] <= wr_data[0];
  always @(posedge clk)
    if (_008_) \mem[1] [1] <= wr_data[1];
  always @(posedge clk)
    if (_008_) \mem[1] [2] <= wr_data[2];
  always @(posedge clk)
    if (_008_) \mem[1] [3] <= wr_data[3];
  always @(posedge clk)
    if (_008_) \mem[1] [4] <= wr_data[4];
  always @(posedge clk)
    if (_008_) \mem[1] [5] <= wr_data[5];
  always @(posedge clk)
    if (_008_) \mem[1] [6] <= wr_data[6];
  always @(posedge clk)
    if (_008_) \mem[1] [7] <= wr_data[7];
  always @(posedge clk)
    if (_001_) \mem[0] [0] <= wr_data[0];
  always @(posedge clk)
    if (_001_) \mem[0] [1] <= wr_data[1];
  always @(posedge clk)
    if (_001_) \mem[0] [2] <= wr_data[2];
  always @(posedge clk)
    if (_001_) \mem[0] [3] <= wr_data[3];
  always @(posedge clk)
    if (_001_) \mem[0] [4] <= wr_data[4];
  always @(posedge clk)
    if (_001_) \mem[0] [5] <= wr_data[5];
  always @(posedge clk)
    if (_001_) \mem[0] [6] <= wr_data[6];
  always @(posedge clk)
    if (_001_) \mem[0] [7] <= wr_data[7];
endmodule

(* dynports =  1  *)
(* hdlname = "read_pointer" *)
(* src = "rtl/read_pointer.v:1.1-28.10" *)
module \$paramod$d85c9bc1fa502815d8902630536652761c9275b3\read_pointer (clk, rst, rd_en, empty, rd_ptr);
  (* src = "rtl/read_pointer.v:5.33-5.36" *)
  input clk;
  wire clk;
  (* src = "rtl/read_pointer.v:6.33-6.36" *)
  input rst;
  wire rst;
  (* src = "rtl/read_pointer.v:7.33-7.38" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/read_pointer.v:8.33-8.38" *)
  input empty;
  wire empty;
  (* src = "rtl/read_pointer.v:10.33-10.39" *)
  output [3:0] rd_ptr;
  reg [3:0] rd_ptr;
  (* src = "rtl/read_pointer.v:19.14-19.29" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  assign _03_ = ~rd_ptr[0];
  assign _01_ = rd_ptr[0] & rd_ptr[1];
  assign _04_ = rd_ptr[0] ^ rd_ptr[1];
  assign _02_ = ~(rd_ptr[2] & _01_);
  assign _05_ = rd_ptr[2] ^ _01_;
  assign _06_ = ~(rd_ptr[3] ^ _02_);
  assign _00_ = rd_en & ~(empty);
  (* src = "rtl/read_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rd_ptr[0] <= 1'h0;
    else if (_00_) rd_ptr[0] <= _03_;
  (* src = "rtl/read_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rd_ptr[1] <= 1'h0;
    else if (_00_) rd_ptr[1] <= _04_;
  (* src = "rtl/read_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rd_ptr[2] <= 1'h0;
    else if (_00_) rd_ptr[2] <= _05_;
  (* src = "rtl/read_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rd_ptr[3] <= 1'h0;
    else if (_00_) rd_ptr[3] <= _06_;
endmodule

(* dynports =  1  *)
(* hdlname = "write_pointer" *)
(* src = "rtl/write_pointer.v:1.1-28.10" *)
module \$paramod$d85c9bc1fa502815d8902630536652761c9275b3\write_pointer (clk, rst, wr_en, full, wr_ptr);
  (* src = "rtl/write_pointer.v:5.33-5.36" *)
  input clk;
  wire clk;
  (* src = "rtl/write_pointer.v:6.33-6.36" *)
  input rst;
  wire rst;
  (* src = "rtl/write_pointer.v:7.33-7.38" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/write_pointer.v:8.33-8.37" *)
  input full;
  wire full;
  (* src = "rtl/write_pointer.v:10.33-10.39" *)
  output [3:0] wr_ptr;
  reg [3:0] wr_ptr;
  (* src = "rtl/write_pointer.v:19.14-19.28" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  assign _03_ = ~wr_ptr[0];
  assign _01_ = wr_ptr[0] & wr_ptr[1];
  assign _04_ = wr_ptr[0] ^ wr_ptr[1];
  assign _02_ = ~(wr_ptr[2] & _01_);
  assign _05_ = wr_ptr[2] ^ _01_;
  assign _06_ = ~(wr_ptr[3] ^ _02_);
  assign _00_ = wr_en & ~(full);
  (* src = "rtl/write_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wr_ptr[0] <= 1'h0;
    else if (_00_) wr_ptr[0] <= _03_;
  (* src = "rtl/write_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wr_ptr[1] <= 1'h0;
    else if (_00_) wr_ptr[1] <= _04_;
  (* src = "rtl/write_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wr_ptr[2] <= 1'h0;
    else if (_00_) wr_ptr[2] <= _05_;
  (* src = "rtl/write_pointer.v:15.1-26.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wr_ptr[3] <= 1'h0;
    else if (_00_) wr_ptr[3] <= _06_;
endmodule

(* dynports =  1  *)
(* hdlname = "fifo_counter" *)
(* src = "rtl/fifo_counter.v:1.1-40.10" *)
module \$paramod$e0708b37338bdb088a3b0307db2b5859402bc745\fifo_counter (clk, rst, wr_en, rd_en, full, empty, count);
  (* src = "rtl/fifo_counter.v:5.29-5.32" *)
  input clk;
  wire clk;
  (* src = "rtl/fifo_counter.v:6.29-6.32" *)
  input rst;
  wire rst;
  (* src = "rtl/fifo_counter.v:7.29-7.34" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/fifo_counter.v:8.29-8.34" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/fifo_counter.v:9.29-9.33" *)
  input full;
  wire full;
  (* src = "rtl/fifo_counter.v:10.29-10.34" *)
  input empty;
  wire empty;
  (* src = "rtl/fifo_counter.v:12.31-12.36" *)
  output [4:0] count;
  reg [4:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/fifo_counter.v:28.26-28.35|C:\\Users\\Hema\\DOWNLO~1\\OSS-CA~1\\bin\\../share/yosys/techmap.v:270.26-270.27" *)
  wire [4:0] _16_;
  assign _16_[0] = ~count[0];
  assign _01_ = rd_en & ~(empty);
  assign _02_ = full | ~(wr_en);
  assign _03_ = _01_ & _02_;
  assign _04_ = ~(count[3] & _03_);
  assign _05_ = ~(count[2] & _03_);
  assign _06_ = ~(count[1] & _03_);
  assign _07_ = count[1] ^ _03_;
  assign _08_ = ~(count[0] & _07_);
  assign _09_ = _06_ & _08_;
  assign _10_ = ~(count[2] ^ _03_);
  assign _11_ = _09_ | _10_;
  assign _12_ = _05_ & _11_;
  assign _13_ = _12_ ? _03_ : count[3];
  assign _14_ = ~(_04_ & _13_);
  assign _16_[4] = ~(count[4] ^ _14_);
  assign _15_ = count[3] ^ _03_;
  assign _16_[3] = ~(_12_ ^ _15_);
  assign _16_[2] = _09_ ^ _10_;
  assign _16_[1] = ~(_16_[0] ^ _07_);
  assign _00_ = ~(_01_ ^ _02_);
  (* src = "rtl/fifo_counter.v:15.1-38.4" *)
  always @(posedge clk, posedge rst)
    if (rst) count[0] <= 1'h0;
    else if (_00_) count[0] <= _16_[0];
  (* src = "rtl/fifo_counter.v:15.1-38.4" *)
  always @(posedge clk, posedge rst)
    if (rst) count[1] <= 1'h0;
    else if (_00_) count[1] <= _16_[1];
  (* src = "rtl/fifo_counter.v:15.1-38.4" *)
  always @(posedge clk, posedge rst)
    if (rst) count[2] <= 1'h0;
    else if (_00_) count[2] <= _16_[2];
  (* src = "rtl/fifo_counter.v:15.1-38.4" *)
  always @(posedge clk, posedge rst)
    if (rst) count[3] <= 1'h0;
    else if (_00_) count[3] <= _16_[3];
  (* src = "rtl/fifo_counter.v:15.1-38.4" *)
  always @(posedge clk, posedge rst)
    if (rst) count[4] <= 1'h0;
    else if (_00_) count[4] <= _16_[4];
endmodule

(* dynports =  1  *)
(* hdlname = "full_logic" *)
(* src = "rtl/full_logic.v:1.1-12.10" *)
module \$paramod$e0708b37338bdb088a3b0307db2b5859402bc745\full_logic (count, full);
  (* src = "rtl/full_logic.v:5.27-5.32" *)
  input [4:0] count;
  wire [4:0] count;
  (* src = "rtl/full_logic.v:7.12-7.16" *)
  output full;
  wire full;
  wire _0_;
  wire _1_;
  wire _2_;
  assign _0_ = ~(count[2] | count[3]);
  assign _1_ = ~(count[0] | count[1]);
  assign _2_ = count[4] & _1_;
  assign full = _0_ & _2_;
endmodule

(* dynports =  1  *)
(* hdlname = "empty_logic" *)
(* src = "rtl/empty_logic.v:1.1-11.10" *)
module \$paramod\empty_logic\ADDR_WIDTH=s32'00000000000000000000000000000100 (count, empty);
  (* src = "rtl/empty_logic.v:4.27-4.32" *)
  input [4:0] count;
  wire [4:0] count;
  (* src = "rtl/empty_logic.v:6.12-6.17" *)
  output empty;
  wire empty;
  wire _0_;
  wire _1_;
  wire _2_;
  assign _0_ = ~(count[4] | count[2]);
  assign _1_ = ~(count[3] | count[0]);
  assign _2_ = _1_ & ~(count[1]);
  assign empty = _0_ & _2_;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/fifo_top.v:1.1-101.10" *)
module fifo_top(clk, rst, wr_en, rd_en, wr_data, rd_data, full, empty);
  (* src = "rtl/fifo_top.v:6.33-6.36" *)
  input clk;
  wire clk;
  (* src = "rtl/fifo_top.v:7.33-7.36" *)
  input rst;
  wire rst;
  (* src = "rtl/fifo_top.v:8.33-8.38" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/fifo_top.v:9.33-9.38" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/fifo_top.v:10.33-10.40" *)
  input [7:0] wr_data;
  wire [7:0] wr_data;
  (* src = "rtl/fifo_top.v:12.33-12.40" *)
  output [7:0] rd_data;
  wire [7:0] rd_data;
  (* src = "rtl/fifo_top.v:13.33-13.37" *)
  output full;
  wire full;
  (* src = "rtl/fifo_top.v:14.33-14.38" *)
  output empty;
  wire empty;
  (* src = "rtl/fifo_top.v:20.21-20.26" *)
  wire [4:0] count;
  (* src = "rtl/fifo_top.v:18.23-18.29" *)
  wire [3:0] rd_ptr;
  (* src = "rtl/fifo_top.v:23.6-23.17" *)
  wire read_enable;
  (* src = "rtl/fifo_top.v:17.23-17.29" *)
  wire [3:0] wr_ptr;
  (* src = "rtl/fifo_top.v:22.6-22.18" *)
  wire write_enable;
  (* src = "rtl/fifo_top.v:96.3-99.2" *)
  \$paramod\empty_logic\ADDR_WIDTH=s32'00000000000000000000000000000100  u_empty_logic (
    .count(count),
    .empty(empty)
  );
  (* src = "rtl/fifo_top.v:64.3-72.2" *)
  \$paramod$e0708b37338bdb088a3b0307db2b5859402bc745\fifo_counter  u_fifo_counter (
    .clk(clk),
    .count(count),
    .empty(empty),
    .full(full),
    .rd_en(rd_en),
    .rst(rst),
    .wr_en(wr_en)
  );
  (* src = "rtl/fifo_top.v:29.3-37.2" *)
  \$paramod$6a1231bad6349c99ef10c6a6a58dbbf16b7d2bdb\fifo_memory  u_fifo_memory (
    .clk(clk),
    .rd_data(rd_data),
    .rd_en(read_enable),
    .rd_ptr(rd_ptr),
    .wr_data(wr_data),
    .wr_en(write_enable),
    .wr_ptr(wr_ptr)
  );
  (* src = "rtl/fifo_top.v:89.3-92.2" *)
  \$paramod$e0708b37338bdb088a3b0307db2b5859402bc745\full_logic  u_full_logic (
    .count(count),
    .full(full)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/fifo_top.v:80.14-84.2" *)
  read_control u_read_control (
    .empty(empty),
    .rd_en(rd_en),
    .read_enable(read_enable)
  );
  (* src = "rtl/fifo_top.v:53.3-59.2" *)
  \$paramod$d85c9bc1fa502815d8902630536652761c9275b3\read_pointer  u_read_pointer (
    .clk(clk),
    .empty(empty),
    .rd_en(read_enable),
    .rd_ptr(rd_ptr),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/fifo_top.v:74.15-78.2" *)
  write_control u_write_control (
    .full(full),
    .wr_en(wr_en),
    .write_enable(write_enable)
  );
  (* src = "rtl/fifo_top.v:42.3-48.2" *)
  \$paramod$d85c9bc1fa502815d8902630536652761c9275b3\write_pointer  u_write_pointer (
    .clk(clk),
    .full(full),
    .rst(rst),
    .wr_en(write_enable),
    .wr_ptr(wr_ptr)
  );
endmodule

(* src = "rtl/read_control.v:1.1-10.10" *)
module read_control(rd_en, empty, read_enable);
  (* src = "rtl/read_control.v:2.12-2.17" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/read_control.v:3.12-3.17" *)
  input empty;
  wire empty;
  (* src = "rtl/read_control.v:5.12-5.23" *)
  output read_enable;
  wire read_enable;
  assign read_enable = rd_en & ~(empty);
endmodule

(* src = "rtl/write_control.v:1.1-10.10" *)
module write_control(wr_en, full, write_enable);
  (* src = "rtl/write_control.v:2.12-2.17" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/write_control.v:3.12-3.16" *)
  input full;
  wire full;
  (* src = "rtl/write_control.v:5.12-5.24" *)
  output write_enable;
  wire write_enable;
  assign write_enable = wr_en & ~(full);
endmodule
